# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Install and Build 🔧 
      run: |
        echo 'TODO build here'
    - name: Deploy 🚀
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }} # This token has to be generated as shown in https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
      run: |
        set -ex
        # use the generated token to autheticate the action
        git remote set-url origin https://mircohaug:${ACCESS_TOKEN}@github.com/ohierro/educa_game.git
        # split of the subtree at frontend/dist (or wherever your frontend is located) and force push it to the gh-pages branch
        # git push origin `git subtree split --prefix frontend/dist master`:gh-pages --force
        git subtree push --prefix dist origin gh-pages
